name = "Quadtree"
uuid = "f668e113-9f8b-4879-aee4-af57b0614260"
authors = ["Jorge Pereira <jorge.brito.json@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
